aq-chat:
  websocketPort: 9090
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 10000
  aliOssConfig:
    endpoint: oss-cn-shenzhen.aliyuncs.com
  aliOssStsConfig:
    accessKeyId:
    accessKeySecret:
    bucketName:
    endpoint: sts.cn-hangzhou.aliyuncs.com
    regionId: cn-hangzhou
    roleSessionName: aqchat-oss-sts
    roleArn:
    durationSeconds: 3600


spring:
  application:
    name: AQChat
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000
      lettuce:
        pool:
          max-active: 32
          max-wait: -1
          max-idle: 16
          min-idle: 8

