aq-chat:
  websocketPort: 9090
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 10000
  aliOssConfig:
    endpoint: oss-cn-shenzhen.aliyuncs.com
  aliOssStsConfig:
    accessKeyId:
    accessKeySecret:
    bucketName:
    endpoint: sts.cn-hangzhou.aliyuncs.com
    regionId: cn-hangzhou
    roleSessionName: aqchat-oss-sts
    roleArn:
    durationSeconds: 3600
  rocketmq:
    producer:
      nameSever: 127.0.0.1:9876
      groupName: AQChat
      retryTimes: 3
      sendTimeOut: 3000
    consumer:
      nameSever: 127.0.0.1:9876


spring:
  application:
    name: AQChat
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aqchat?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl