aq-chat:
  websocketPort: 9090
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 10000
  aliOssConfig: #OSS控制台查看
    endpoint: 
  aliOssStsConfig: #前往阿里sts文档获取以下配置
    accessKeyId:
    accessKeySecret:
    bucketName: aqchat
    endpoint:
    regionId: cn-hangzhou
    roleSessionName:
    roleArn:
    durationSeconds: 3600
  rocketmq:
    producer:
      nameSever: 127.0.0.1:9876
      groupName: AQChat
      retryTimes: 3
      sendTimeOut: 3000
    consumer:
      nameSever: 127.0.0.1:9876
  aiConfig: #前往阿里百炼平台获取
    apiKey:
    model: qwen-max #模型名称


spring:
  application:
    name: AQChat
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aqchat?useUnicode=true&characterEncoding=UTF-8
    username: aqchat
    password:

  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl